version: '3.4'

services:
  fuzzer-js:
    image: fuzzer-js
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3030:3000
    volumes:
      - ./app:/usr/src/app